Script started on Mon 13 Mar 2017 11:41:49 AM CST
[01;32mandmichi@andmichi[01;34m ~/lab1/lab1 $[00m lsgit clone https://github.com/Kazumachi124170/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Caccount>[K[1Pgithub [2P<yourgit clone https://github.com/[16Ponfig -l[3Pwhoami;pwdiami;pwdoami;pwdgit config -llone https://github.com/<your[Kgithub account>git clone https://github.com/Kazumachi124170/lab1.git[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kg++ -o hw1_2 hw1_2.cpp
[01;32mandmichi@andmichi[01;34m ~/lab1/lab1 $[00m ./hw1_2
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1
[01;32mandmichi@andmichi[01;34m ~/lab1/lab1 $[00m exit

Script done on Mon 13 Mar 2017 11:42:48 AM CST
